server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: property-management-service
  jpa:
    hibernate:
      ddl-auto: none # not working !
    properties:
      # temporarily solution to prevent hibernate from creating tables , (ddl-auto: none) will not work
      hibernate:
        hbm2ddl:
          auto: none
        # ----------------------
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/property_management # use this if you want to run the app locally , if no postgresql installed , use docker-compose in _resources/docker
    username: idder
    password: idderjamh
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/public/db.public.changelog-master.yml
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
aws:
  access:
    key: ${AWS_ACCESS_KEY:AKIA5RGPWXNPZ5OGWOCE}
  secret:
    key: ${AWS_SECRET_KEY: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}
  s3:
    bucket: resitechbucket
    region: eu-north-1
logging:
  level:
    org:
      springframework:
        web: TRACE
    liquibase: TRACE
